### PR TITLE
Add function lxw_exists_control_chars to utility

### PR DESCRIPTION
**Pull request by viest**
Using the CPU instruction set to optimize the control of character retrieval, when the character length exceeds or equals 16, it has a significant performance improvement.

### Number of cells

500,000 rows * 20 columns

### Char length

26

### CODE REVIEW

**Comment by jmcnamara** [comment]
Thanks. Could you add a sample test program here, or in a separate issue, that could be used to determine the relative performance.

**Comment by viest** [comment]
When the string length is less than 16, compared with the standard library `strpbrk`, there is a 5 times performance improvement. As the string length increases, we can get up to 10 times the performance improvement. For the optimization mode, this improvement will be Awesome.

```
ASCII: 

strpbrk                  , loop: 1000, str len: 9，time:0.000122
lxw_exists_control_chars , loop: 1000, str len: 9，time:0.000020
strpbrk                  , loop: 10000, str len: 9，time:0.001174
lxw_exists_control_chars , loop: 10000, str len: 9，time:0.000201
strpbrk                  , loop: 100000, str len: 9，time:0.011563
lxw_exists_control_chars , loop: 100000, str len: 9，time:0.002018
strpbrk                  , loop: 1000, str len: 26，time:0.000296
lxw_exists_control_chars , loop: 1000, str len: 26，time:0.000059
strpbrk                  , loop: 1000, str len: 52，time:0.000564
lxw_exists_control_chars , loop: 1000, str len: 52，time:0.000057
strpbrk                  , loop: 1000, str len: 78，time:0.000854
lxw_exists_control_chars , loop: 1000, str len: 78，time:0.000081
strpbrk                  , loop: 1000000, str len: 26，time:0.246461
lxw_exists_control_chars , loop: 1000000, str len: 26，time:0.048152
strpbrk                  , loop: 1000000, str len: 52，time:0.455256
lxw_exists_control_chars , loop: 1000000, str len: 52，time:0.046717
strpbrk                  , loop: 1000000, str len: 78，time:0.721552
lxw_exists_control_chars , loop: 1000000, str len: 78，time:0.067716

NON ASCII: 

strpbrk                  , loop: 1000, str len: 162，time:0.001447
lxw_exists_control_chars , loop: 1000, str len: 162，time:0.000072
strpbrk                  , loop: 100000, str len: 162，time:0.156455
lxw_exists_control_chars , loop: 100000, str len: 162，time:0.007992
```

<details>
<summary>Benchmark Code</summary>

```c
//
// Created by viest on 2020/7/1.
//

#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>

#ifdef __SSE2__
#include <emmintrin.h>
#endif

enum lxw_boolean
{
    LXW_FALSE,
    LXW_TRUE
};

unsigned char
lxw_exists_control_chars(const char *string);

void
benchmark(int loop, const char *string);

int main()
{
    printf("ASCII: \n");

    char *string1 = "ABCDEFGHI";
    benchmark(1000, string1);

    char *string2 = "ABCDEFGHI";
    benchmark(10000, string2);

    char *string3 = "ABCDEFGHI";
    benchmark(100000, string3);

    char *string4 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000, string4);

    char *string5 = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000, string5);

    char *string6 = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000, string6);

    char *string7 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000000, string7);

    char *string8 = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000000, string8);

    char *string9 = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    benchmark(1000000, string9);

    printf("NON ASCII: \n");

    char *string10 = "中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文";
    benchmark(1000, string10);

    char *string11 = "中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文";
    benchmark(100000, string11);
}

void benchmark(int loop, const char *string)
{
    int   i;
    float timeuse;

    struct timeval start, end;

    size_t len = strlen(string);

    gettimeofday(&start, NULL);
    for (i = 0; i < loop; i++) {
        strpbrk(string, "\x01\x02\x03\x04\x05\x06\x07\x08\x0B\x0C"
                        "\x0D\x0E\x0F\x10\x11\x12\x13\x14\x15\x16"
                        "\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F");
    }
    gettimeofday(&end, NULL);
    timeuse = 1000000 * (end.tv_sec - start.tv_sec) + end.tv_usec - start.tv_usec;
    timeuse /= 1000000;
    printf("strpbrk                  , loop: %d, str len: %zu，time:%f\n", loop, len, timeuse);

    gettimeofday(&start, NULL);
    for (i = 0; i < loop; i++) {
        lxw_exists_control_chars(string);
    }
    gettimeofday(&end, NULL);
    timeuse = 1000000 * (end.tv_sec - start.tv_sec) + end.tv_usec - start.tv_usec;
    timeuse /= 1000000;

    printf("lxw_exists_control_chars , loop: %d, str len: %zu，time:%f\n", loop, len, timeuse);
}

/* Find control characters in the string.
 * \x01\x02\x03\x04\x05\x06\x07\x08\x0B\x0C
 * \x0D\x0E\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F */
unsigned char
lxw_exists_control_chars(const char *string)
{
    size_t str_len = strlen(string);

#ifdef __SSE2__
    /* If the CPU supports the SSE2 instruction set, use the SSE2 instruction set to quickly filter. */
    /* Filtering 16 characters at a time. */
    if (str_len >= 16) {
        const __m128i _char_nul   = _mm_set1_epi8('\x00');
        const __m128i _char_ht    = _mm_set1_epi8('\x09');
        const __m128i _char_lf    = _mm_set1_epi8('\x0A');
        const __m128i _char_space = _mm_set1_epi8('\x20');

        while (str_len >= 16) {
            __m128i _tm, _eq;
            __m128i _value = _mm_loadu_si128((__m128i *) string);

            /* There are no control characters in the current string */
            _tm = _mm_max_epu8(_value, _char_space);
            _eq = _mm_cmpeq_epi8(_value, _tm);
            if (_eq[0] == -1 && _eq[1] == -1)
                goto next;

            /* There are control characters in the current string */
            /* \x0B\x0C\x0D\x0E\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F */
            _tm = _mm_min_epu8(_value, _char_lf);
            _eq = _mm_cmpeq_epi8(_char_lf, _tm);
            if (_eq[0] == -1 && _eq[1] == -1)
                return LXW_TRUE;

            /* Continue \x09 */
            _tm = _mm_min_epu8(_value, _char_ht);
            _eq = _mm_cmpeq_epi8(_char_ht, _tm);
            if (_eq[0] && _eq[1])
                goto next;

            /* There are control character in the current string */
            /* \x01\x02\x03\x04\x05\x06\x07\x08 */
            _tm = _mm_min_epu8(_value, _char_nul);
            _eq = _mm_cmpeq_epi8(_char_nul, _tm);
            if (_eq[0] == -1 && _eq[1] == -1)
                return LXW_TRUE;

            next:

            string += 16;
            str_len -= 16;
        }
    }
#endif

    /* Filter the remaining characters. */
    /* If the SSE2 instruction set is not supported, please use the conventional way to filter. */
    /* But currently all x86 architecture CPUs on the market support the SSE2 instruction set. */
    while (str_len > 0) {
        unsigned char _string = *string;

        if (_string < '\x20' && ((_string > '\x00' && _string < '\x09') || _string > '\x0A')) {
            return LXW_TRUE;
        }

        ++string;
        --str_len;
    }

    return LXW_FALSE;
}
```

</details>

**Comment by jmcnamara** [comment]
Hi,

I finally got around to looking at this.

To test the effect of the strpbrk() call I ran the following test program:

```C
#include <stdlib.h>
#include "xlsxwriter.h"

int main(int argc, char  *argv[]) {

    int max_row;
    int max_col;
    int max_length;
    char string[] = "abcdefghijklmnopqrstuvwxyz_";

    if (argc < 3) {
        puts("usage: perf_test row_num col_num string_length");
        return -1; 
    }

    max_row    = atoi(argv[1]);
    max_col    = atoi(argv[2]);
    max_length = atoi(argv[3]);

    if (max_length > 26) {
        puts("usage: perf_test row_num col_num string_length");
        puts("       string_length must be <= 26");
    }

    string[max_length] = '\0';
    printf("rows = %d x cols = %d x string length = %d\n", max_row, max_col, max_length);


    lxw_workbook_options options = {.constant_memory = LXW_TRUE};
    lxw_workbook  *workbook  = workbook_new_opt("test.xlsx", &options);
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    for (int row_num = 0; row_num < max_row; row_num++)
        for (int col_num = 0; col_num < max_col; col_num++)
            worksheet_write_string(worksheet, row_num, col_num, string, NULL);

    workbook_close(workbook);

    return 0;
}
```

This uses `constant_memory` so that each string is checked for each write().

I put the file, called perf_test.c, in the examples directory of the repo and compiled it like this:

```bash
CFLAGS="-O3" make examples V=1
```
Then I ran it and timed it as follow for the number of row/cols/string length that you gave above:

```bash
time ./examples/perf_test 500000 20 26
```

Here are the results (for three runs) for the base case (no optimization):

```bash
# Case 1
$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m29.981s
user	0m26.264s
sys	0m3.623s

$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m29.956s
user	0m26.261s
sys	0m3.599s

$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m29.691s
user	0m26.010s
sys	0m3.567s
```

Then I added an optimization (like the non-SSE part of your example:

```bash
# Case 2
$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m24.973s
user	0m21.267s
sys	0m3.583s
~/Development/libxlsx/libxlsxwriter (master)$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m25.013s
user	0m21.238s
sys	0m3.632s
~/Development/libxlsx/libxlsxwriter (master)$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m25.037s
user	0m21.337s
sys	0m3.575s
```
Then I ran it with your changes:

```bash
# Case 3
$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m24.456s
user	0m20.774s
sys	0m3.600s

$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m24.400s
user	0m20.711s
sys	0m3.591s

$ time ./examples/perf_test 500000 20 26
rows = 500000 x cols = 20 x string length = 26

real	0m24.508s
user	0m20.828s
sys	0m3.571s
```

Taking the median value from each of the three runs in each of the three case gave:



29.691 |  - | Base case
-- | -- | --
25.013 | 16% | Simpler non-strpbrk check.
24.456 | 18% | SSE code


The SSE case is clearly better but not by enough to add a new compile path and code I can't maintain.

I've pushed the case 2 to master in 9e8bc95b452d7e9d4b0fe9834a0fcfbf5ee7a91e. You can try it out and see how you get on. If you think you really need the SSE code you can patch your version locally.

Let me know how you get on.

**Comment by jmcnamara** [comment]
This version is about 1% faster than the 16% case, but I'll need to test it with some other compilers:

```C
uint8_t
lxw_has_control_characters(const char *string)
{
    while (string) {
        /* 0xE0 == 0b11100000 masks values > 0x19 == 0b00011111. */
        if (!(*string & 0xE0) && *string != 0x0A && *string != 0x09)
            return LXW_TRUE;

        string++;
    }

    return LXW_FALSE;
}
```

**Comment by jmcnamara** [comment]
I've pushed the non-SSE fix above in version 1.0.0 of libxlsxwriter.

Thanks for pointing out the bottleneck. Closing.

**Pull request closed without merging**
