### PR TITLE
Add workbook_default_format

### PR DESCRIPTION
**Pull request by Paxa**
* add `workbook_default_format`
* `workbook_add_format` will make copy of default format
* `format->font_size = -1` will set to excel’s default

### CODE REVIEW

**Comment by Paxa** [comment]
Related to https://github.com/jmcnamara/libxlsxwriter/issues/96

**Comment by jmcnamara** [comment]
Apologies if I wasn't clear on this in but this isn't something that I want to add since it has side effects on image and chart sizing that aren't easy to fix.

So I am going to close this as "won't fix".

**Comment by Paxa** [comment]
It was clear that you don't want this feature, but the reason behind it is not totally clear:

1. we can change font size now and it will break image and chart sizing and it's ok, but letting to setting default font size is not OK
2. you are making excel libs for other languages too, but it doesn't mean that all them should lack same feature (it should be easy to implement I think)

I expected your reaction, but may be somebody will need it

**Comment by jmcnamara** [comment]
> 1. we can change font size now and it will break image and chart sizing and it's ok, but letting to setting default font size is not OK

Correct. The first behaviour is [documented](https://libxlsxwriter.github.io/worksheet_8h.html#a4529d77bcefcf478b8209f46fe730f6f) like this:

> Note: The scaling of a image may be affected if is crosses a row that has its default height changed due to a font that is larger than the default font size or that has text wrapping turned on. To avoid this you should explicitly set the height of the row using worksheet_set_row() if it crosses an inserted image.

The second behaviour is different. If the user wants to set it themselves then that is okay but it isn't supported.

> 2. you are making excel libs for other languages too, but it doesn't mean that all them should lack same feature (it should be easy to implement I think)

This part is probably more important to me than it is to the end user. I need to support and maintain these libraries long after an end users loses interest. As such I can only put in features that I think make sense and can support into the future. And when they are added then I need to add tests and documentation. However, I haven't seen enough feature requests for this feature yet (across all four xlsx writer projects).

**Comment by Paxa** [comment]
I hope this can be added in some way or another some day. Until then, I'll have to maintain my own fork for https://github.com/Paxa/fast_excel :(

I think, user's of library should be able to make a file displayed with viewer's default settings (same as if you just create a file manually without changing font size in excel app)

**Comment by jmcnamara** [comment]
My reasons for not supporting a modifiable default format are still the same: it would break the sizing of objects like images and charts. So this is still a "won't fix" for me. Sorry.

**Comment by Paxa** [comment]
How about just allow set viewer's default font size? (no documentation, and make comment about dangerous behavior)

```c
workbook.use_viewers_default_font_size_i_know_it_will_break_images_and_charts(true);
```

Your default font-size is 11 right? I use excel for mac and it comes with default font set to 12, then 11 looks small. Others may have different preferences, and they can change it in settings. IMO should let people use what they want (and what they put in settings), don't insist on tea spoon for soup and vice versa

Screenshot 2023-12-29 at 19 40 05

I use your library for 6 years or so, and never had issue with images and charts, also nobody report this to me. (setting default font size is [3rd line in readme](https://github.com/Paxa/fast_excel/blob/788c94231405e80ce307ac29ce2c85d37f2a41fa/README.md?plain=1#L8) example, I think many people used it)

**Pull request closed without merging**
