### PR TITLE
Add worksheet_merge_range to merge ranges of cells

### PR DESCRIPTION
**Pull request by bradediger**
I noticed that cell merging was missing from libxlsxwriter. I added a simple `worksheet_merge_range` function that doesn't support formatting or setting data but rather merges predefined cells, for example:

```c
worksheet_write_string(worksheet, 0, 0, "Merged two rows and two columns", NULL);
worksheet_merge_range(worksheet, 0, 0, 1, 1);
```

It's pretty simple right now but it's working well for me. Let me know if you have any comments or suggestions.

Thanks for making libxlsxwriter available; it's been quite helpful!

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi Brad,

Thanks for that. Bonus points for adding tests.

I already have some skeleton code and tests for merged ranges so I probably won't merge this. Merged ranges are on the timeline for the next but one release.

P.S. I'm trying to gauge how and where people are using this library. What OS are you using?

John

**Comment by bradediger** [comment]
@jmcnamara Thanks for the feedback. No worries -- this solved a problem I have currently and I anticipate seeing how you solve it when it makes release. I don't know all of the ins and outs of this part of SpreadsheetML; I'd welcome a more principled solution.

I'm using libxlsxwriter via some Haskell FFI bindings I wrote because it was superior to the native Haskell solutions I found (empirically, it is much faster, too). We are developing on OS X and deploying on CentOS Linux.

**Comment by jmcnamara** [comment]
Hi Brad,

Thanks for the feedback. FFI bindings for Haskell sounds interesting. If it is or becomes open source you should send me a link. I'd like to do something similar for Jula at some stage.

Anyway, I've pushed the `merge_range()` implementation. If you get a chance you can try it out. [Here are the docs](http://libxlsxwriter.github.io/worksheet_8h.html#ac15d2e82b73308458e9cdebeffdd46e6).

Thanks for your input.

John

**Comment by bradediger** [comment]
Thanks John! I considered open-sourcing the bindings but they are currently in flux as I have been trying to decide the proper Haskell API for my needs. All the typical problems of extracting open source from proprietary projects: 1) API surface that isn't needed isn't built, and 2) the API is much more suited to our own particular needs than any generic implementation.

Thanks for referring me to the new implementation -- it's more robust and complete than mine. I will be switching over to this on my own project.

Cheers,
-be

**Pull request closed without merging**
