### PR TITLE
Update FindZLib CMake module

### PR DESCRIPTION
**Pull request by evanmiller**
The current version errors out on macOS 10.14 Mojave:

```
$ cmake .
CMake Error at cmake/FindPackage.cmake:180 (message):
  Unable to find requested ZLIB libraries.
Call Stack (most recent call first):
  cmake/FindZLIB.cmake:123 (RequiredPackageFound)
  CMakeLists.txt:163 (find_package)


zlib version:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIBRARY
    linked by target "xlsxwriter" in directory /XXX/libxlsxwriter

-- Configuring incomplete, errors occurred!
```

This commit includes the FindZLib module from CMake 3.13, as well as additional scripts that FindZLib depends on.

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi Evan,

For future reference PR should start with an issue tracker. See [Pull Requests and Contributing to Libxlsxwriter](https://github.com/jmcnamara/libxlsxwriter/blob/master/CONTRIBUTING.md).

I don't like the idea of including third party files to fix CMake. Isn't there any way to fix this within the existing CMake code?

@Alexhuszagh can you take a look at fixing this issue.

John

**Comment by evanmiller** [comment]
Actually, simply deleting `cmake/FindZLib.cmake` ought to do the trick. CMake will then look for the system-installed FindZLib, which is included with CMake 3.13.

**Comment by Alexhuszagh** [comment]
@evanmiller That sounds like a good solution, to be fair. It was mostly a work-around for another build system (I believe with the MSVC static runtime), and I tested it with MacOS like 2 years back, but we should prefer upstream whenever possible. FindZlib has been supported for quite a long time (since at least CMake 3.0, which we require anyway).

**Comment by Alexhuszagh** [comment]
@evanmiller Let me update my fork and see if Appveyor has any issues with the MSVC static runtime with CMake upstream, if so, I think deleting FindZlib is in the interests of everyone.

**Comment by jmcnamara** [comment]
@evanmiller, @Alexhuszagh 

Could we resurrect this as an Issue and PR that deletes FindZlib? Even if it requires specifying a minimum CMake version.

**Pull request closed without merging**
