### PR TITLE
Add Podspec

### PR DESCRIPTION
**Pull request by lrossi**
Adds a Podspec file for CocoaPods (https://cocoapods.org) to simplify the integration of the library in iOS projects.

### CODE REVIEW

**Comment by jmcnamara** [comment]
Thanks for that.

John.

**Comment by lrossi** [comment]
Thanks for merging. The podspec should now be pushed to the CocoaPods trunk so that the library will be available from the main CocoaPods distribution channel.

If you want, I can do this and keep the podspec in sync with subsequent library updates. (Of course, I would add you as owner in the CocoaPods trunk).

Otherwise, if you prefer you can push the podspec yourself:

https://guides.cocoapods.org/making/getting-setup-with-trunk
  
Thank you

**Comment by jmcnamara** [comment]
Hi,

I'll do it and make it part of the release process in future.

BTW, did you have any issues with the zlib version used by the library and the default version on iOS? I had some bug report about that.

John

**Comment by lrossi** [comment]
Hi John,

perfect, thanks!

As regards compiling on iOS, I only encountered an issue with missing type ‘z_crc_t’ (similar to #5) and I circumvented it by adding the NOCRYPT=1 and NOUNCRYPT=1 flags as suggested here: http://kvurd.com/blog/building-libxlsxwriter-for-ios/

Beside that, I was able to compile the included minzip dependency without needing to downgrade zlib. I’ve tested the pod on iOS 8 and I’m using it to generate some Excel files in an app I’m working on, and it works great. Oh by the way, thanks for such an amazing library :)

If you have access to an OS X installation with Xcode installed, you can install CocoaPods and try the pod compilation by running:

	pod lib lint --verbose libxlsxwriter.podspec

Also, if you are interested in it, I was thinking about creating a sample iOS project to go along with the pod. Something like a simple app where you can select among the examples you already provided and then see the output through an iOS’s web view (that can render Excel files). Right now I’m working on deadlines, but I should be able to work on it in a few weeks (if no one else offers to do it before, of course).

**Comment by jmcnamara** [comment]
> Also, if you are interested in it, I was thinking about creating a sample iOS project to go along with the pod. Something like a simple app where you can select among the examples you already provided and then see the output through an iOS’s web view (that can render Excel files).

That sounds great and I think it would be really useful. It would probably be better as a standalone repo on GitHub that people could use to get started.


> but I should be able to work on it in a few weeks (if no one else offers to do it before, of course).

Take your time. Whenever you get a chance.:-)

**Comment by jmcnamara** [comment]
Just to let you know that I pushed the spec to the CocoaPods trunk.

There are some pod lint warnings that need to be fixed. I'll do that and add the the pod install method to the next release.

**Comment by jmcnamara** [comment]
I've fixed the lint warnings and (hopefully) set it up to work with iOS and OS X. If you get a chance to test it let me know.

**Comment by lrossi** [comment]
I finally had a chance to put together iOS and Mac example projects in Objective-C and Swift:

https://github.com/lrossi/libxlsxwriterCocoaExamples

Please take a look at them when you have time and of course feel free to share any suggestions. Thanks!

**Comment by jmcnamara** [comment]
Wow, that's great. I love the gif. :-)

I'll try it out on the weekend.

John

**Pull request merged**
