### PR TITLE
Fix including xlsxwriter as a CocoaPod on macOS.

### PR DESCRIPTION
**Pull request by MrMage**
Explanation for this change:

Previously, CocoaPods would set up the framework target such that `xlsxwriter.h` would appear in the framework's main directory, alongside the `xlsxwriter` binary. It appears that the `codesign` utility only expects binaries in that directory, though, with all headers being in the `Headers` subdirectory (otherwise it fails with an `xlsxwriter.h: code object is not signed at all` message). This change modifies the header_mappings_dir to ensure that `xlsxwriter.h` is in `Headers`, with all other headers in `Headers/xlsxwriter`, and adjusts the paths in the module map accordingly.

In addition, the umbrella header is modified to include Foundation rather than UIKit, as the former is sufficient to compile the module while the latter is not available on macOS.

This change fixes compiling, signing and linking with the module on my macOS target. However, I haven't reviewed its correctness for iOS or other implications (although I would expect everything to work), so please review these four lines carefully ;-)

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi,

Thanks for this. A few question below.

What exactly is it fixing? 

Also, could you describe the steps to reproduce the error?

Does this error happen with the latest libxlsxwriter cocoapod?

Does it happen with the latest pod version (or older versions).

> Previously, CocoaPods would set up the framework target such that xlsxwriter.h would appear in the framework's main directory,

Previous to when/what?


> However, I haven't reviewed its correctness for iOS or other implications (although I would expect everything to work), so please review these four lines carefully ;-)

That's the worrying part. ;-)

Anyway, start with some answers to the questions above and/or any other helpful information. Do that in a new Issue (if this is an issue) and link to this PR at the end. I'll see if I can get someone to verify the issue and the fix (I don't use XCode myself).

John

**Comment by lrossi** [comment]
Thanks for spotting the issue and providing a good fix. I’ll take some more time to do further tests, but I wanted to provide a feedback in the meantime.

Bad news: it seems this is breaking iOS projects that build the pod as a static library (i.e. without `use_frameworks!`), because of location of headers included by  `xlsxwriter.h`; it might not be easy to support both framework and static library variants in the same Podspec without modifying the library's headers.

Good news: building pods as framework is quickly becoming the most common use case even with Objective-C, and I think it is more important to provide proper support for building as a framework on macOS than it is to strive for legacy compatibility at all costs (as obsolescence is running a lot faster on iOS than on most other platforms 🙂). If we don't find any better solution and decide to go down this route, we could add a note in the documentation requiring `use_frameworks!` and pointing legacy iOS projects to an older version of the library.

I’ll do some more investigations and get back to you.

**Comment by MrMage** [comment]
Thank you for investigating this! Would there maybe be a workaround for the static library use case by changing some Xcode project settings to look for the header in the correct directory?

Other than that, are there any updates on this?

**Comment by MrMage** [comment]
Ping?

**Comment by jmcnamara** [comment]
> Ping?

I still have a general problem with a lack of time and this PR isn't risk free since it breaks static library build as pointed out by @lrossi above. So I can't just hit the merge button as it it.

So, in order to merge this it will need a few changes/additions:

- [ ] Remove the doc fix and submit it as a separate PR.
- [ ] Submit the PR as a single commit. Currently it has a merge commit in it.
- [ ] Let me know how the docs can be modified to support this change. Do I need to add a note about using `use_frameworks!`, etc: https://libxlsxwriter.github.io/getting_started.html#gsg_cocoapods

**Comment by jmcnamara** [comment]
I've made the doc fix and pushed it to master. How did you find it? Did you get a doxygen warning or did you just find it by reading the docs?

**Comment by MrMage** [comment]
IIRC Xcode 8 and up can parse Doxygen comments and display warnings for them.

I'm also quite busy right now - will get back to you about the Pod change soon.

**Comment by jmcnamara** [comment]
@MrMage Could you clean up the 3 issues above and rebase this PR. Thanks.

**Comment by MrMage** [comment]
Sorry for the delay. **I have created #127 which contains only the relevant changes.** So please close this PR and merge #127 instead.

About compatibility with Static-Library CocoaPods: This is still possible — you just need to use a different include path. As an example, I have created https://github.com/MrMage/libxlsxwriter-test-staticlibrary/blob/master/libxlsxwriter-test-staticlibrary/ViewController.m.

So I'd suggest augmenting the documentation to mention that you should import the libxlsxwriter header via

    #import <libxlsxwriter/xlsxwriter/xlsxwriter.h>

when _not_ using `use_frameworks!` and via

    @import xlsxwriter;

otherwise.

**Comment by jmcnamara** [comment]
Superseded by #127. Closing.

**Pull request closed without merging**
