### PR TITLE
Fix DESTDIR typo

### PR DESCRIPTION
**Pull request by sjmulder**
For #265

### CODE REVIEW

**Comment by jmcnamara** [comment]
Could you also fix this typo highlighted in #265 as part of this PR. And maybe change the commit message to something like "Fix makefile typos.":

```diff
diff --git a/Makefile b/Makefile
index 1af613c..df65c45 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ ifdef V
 Q=
 endif

-DESTIDR ?=
+DESTDIR ?=
 PREFIX  ?= /usr/local

 PYTEST ?= py.test
@@ -46,7 +46,7 @@ clean :
 	$(Q)rm -rf test/functional/__pycache__
 	$(Q)rm -f  test/functional/*.pyc
 	$(Q)rm -f  lib/*
-ifndef USE_STANDARD_TMPFILE
+ifndef USE_SYSTEM_MINIZIP
 	$(Q)$(MAKE) clean -C third_party/minizip
 endif
 ifndef USE_STANDARD_TMPFILE
```

**Comment by jmcnamara** [comment]
Merged. Thanks.

**Comment by sjmulder** [comment]
Sorry for not getting around to fixing the other thing!

**Comment by jmcnamara** [comment]
No problem. Thanks for the fix.

**Pull request merged**
