### PR TITLE
Respect INSTALL_DIR for -install_name

### PR DESCRIPTION
**Pull request by sjmulder**
Issue #209

### CODE REVIEW

**Comment by sjmulder** [comment]
Hi, anything blocking this?

**Comment by jmcnamara** [comment]
Hi @sjmulder,

Nothing is blocking it. I just didn't have time to look at it, even though it is a small fix.

I think I wanted to check if it would be worth allowing PREFIX as well as INSTALL_DIR where one can override the other. Would that help you, or be more consistent, from the packaging side?

John

**Comment by sjmulder** [comment]
Fair enough on the review side, didn't mean to be pushy.

I'd say replace `INSTALL_DIR` with the more common `DESTDIR` and `PREFIX`, e.g.:

    DESTDIR ?=
    PREFIX  ?= /usr/local/

    install: [...]
        install -d $(DESTDIR)$(PREFIX)/lib
        install -d $(DESTDIR)$(PREFIX)/include
        install -m 755 lib/*     $(DESTDIR)$(PREFIX)/lib/
        install -m 644 include/* $(DESTDIR)$(PREFIX)/include/

`PREFIX` is the final location on the user's system. `DESTDIR` could be staging directory for a package build, a chroot, etc. The distinction is important because you don't want `DESTDIR` to end up in paths compiled into the program, e.g. the location of a helpfile or library.

**Comment by sjmulder** [comment]
Now that I look at the PR again, it seems like it wouldn't deal with a `DESTDIR` correctly. Currently pkgsrc sets `INSTALL_DIR=${DESTDIR}${PREFIX}` which would end passing `-install_dir /path/to/workdir/usr/pkg/lib/libxlsxwriter.so` to the linker. But it does work.

In any case I'd be happy to pick up refactoring the Makefiles to use `DESTDIR` and `PREFIX`, if you're OK with it.

**Comment by jmcnamara** [comment]
Yes, that is fine with me. You can modify or resubmit this PR to include the changes. Note, the patch will also need to change the docs when they refer to `INSTALL_DIR`: http://libxlsxwriter.github.io/getting_started.html

**Comment by jmcnamara** [comment]
But can you add an issue to track it separate from the PR. Thanks.

**Comment by sjmulder** [comment]
Of course, issue split off as #216. Thanks.

**Pull request closed without merging**
