### PR TITLE
Zig package

### LINKED ISSUE #401: Feature Request: Add zig package
The purpose of this proposal is to allow Zig developers to use libxlsxwriter in their projects without the need for git modules or any other external tool.

`zig-pkg` is still experimental and will be available in the v0.11.0 release - expected at the end of May.

Theoretically it works similar to `go mod` or `fetchContent (cmake)`.

### PR DESCRIPTION
**Pull request by kassane**
closes #401

### How to use

* Download [Zig v0.11 or higher](https://ziglang.org/download)
* Make on your project `build.zig` & `build.zig.zon` file

e.g:

* **build.zig**
```zig
    const libxlsxwriter_dep = b.dependency("libxlsxwriter", .{ // <== as declared in build.zig.zon
        .target = target, // the same as passing `-Dtarget=<...>` to the library's build.zig script
        .optimize = optimize, // ditto for `-Doptimize=<...>`
    });
    const libxlsxwriter = libxlsxwriter_dep.artifact("xlsxwriter"); // <== has the location of the dependency files (libxlsxwriter)
    /// your executable config
    exe.linkLibrary(libxlsxwriter); // <== link libxlsxwriter
    exe.installLibraryHeaders(libxlsxwriter); // <== get copy libxlsxwriter headers to zig-out/include 
```
* **build.zig.zon**
```zig
.{
    .name = "example",
    .version = "0.1.0",
    .dependencies = .{
        .libxlsxwriter = .{
            .url = "https://github.com/jmcnamara/libxlsxwriter/archive/[tag/commit-hash].tar.gz",
            .hash = "[multihash - sha256-2]",
        },
    },
}
```

### More info about zig-pkg
- https://github.com/ziglang/zig/pull/14265
- https://github.com/ziglang/zig/issues/14307

### CODE REVIEW

**Comment by jmcnamara** [comment]
How would a zig developer use this to build a zig compatible library?

**Comment by kassane** [comment]
> How would a zig developer use this to build a zig compatible library?

Hi, @jmcnamara 

Using that build the developers could choose to create a binding on top of the original library or access the library directly.

In other words, do you remember the binding built by me? [zig-xlsxwriter](https://github.com/kassane/zig-xlsxwriter)

Well, with this change, not only could that project benefit from the library addition be downloaded, build and run with the included binding (another project) or also, users can **bypass my binding** and use the library directly with `@cImport/@cInclude` (`zig translate-c` inside) to auto-generate a binding, regardless of the user-binding project that me or any other developers.

**Comment by kassane** [comment]
### Pointer 2

Using zig toolchain does not exactly mean that need to create a ziglang project, could replace the makefile, cmake, or any other conventional tool with zig.
zig toolchain is pure-LLVM buildtools (replaces: build-essential/base-devel - does not include dbgs or binutils).

**Comment by jmcnamara** [comment]
In general I'd prefer not to add this type of configuration to the root directory. I made an exception for iOS and now there are too many Coacoa and other related files as well as several PRs.

I prefer the VPG and Homebrew approaches where the package updates are in an external repository, like this: https://vcpkg.roundtrip.dev/ports/libxlsxwriter

However, I like Zig as a language and would like to support it so if you agree to support the library additions and make any fixes then I will merge it.

**Comment by kassane** [comment]
OK!
I will even complete support for zlib and minizip dependencies. (Optional install)

**Comment by jmcnamara** [comment]
Ok. Merged. Thanks!

**Pull request merged**
