### PR TITLE
Fix #166 use GNUInstallDirs cmake module

### LINKED ISSUE #166: Please honours library layout
For now, installation layout is hardcoded

        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib

Most Linux distributions use a multi-arch layout (/usr/lib64 in RPM distro, /usr/lib/x86_64... on .deb distro, etc)

Using `${CMAKE_INSTALL_LIBDIR}` seems a common practice

### PR DESCRIPTION
**Pull request by remicollet**
I'm not 100% sure  of minimal version required, but at least 3.0 is ok (and raised to 3.1 by pr #168)

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
@jmcnamara I'm should base my PR off of this, since @remicollet did most of the work.
@remicollet, can you move `INCLUDE(GNUInstallDirs)` to below the the following lines and use the lower-case convention, since the rest of the CMake commands are currently in lowercase?

```diff
# INSTALL
# -------

+include(GNUInstallDirs)
```

**Comment by Alexhuszagh** [comment]
Already done, nevermind....

**Comment by remicollet** [comment]
include moved.

**Comment by Alexhuszagh** [comment]
@remicollet One more (extraordinarily minor) comment: can you change `INCLUDE` to `include`? It's just a convention: I use all lowercase for CMake commands, I'd rather keep it consistent to keep a common convention.

**Comment by jmcnamara** [comment]
Merged with thanks.

@Alexhuszagh you can fix up naming issues in your PR.

**Pull request merged**
