### PR TITLE
fix library name in Makefile

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Comment by jmcnamara** [comment]
Whoops. Thanks. Merging.

**Comment by dotlambda** [comment]
Do you test on Linux? I discovered this while trying to build sc-im with XLSX_EXPORT support.

**Comment by dotlambda** [comment]
A new release with this fix would be nice btw.

**Comment by jmcnamara** [comment]
> Do you test on Linux?

I do. Although clearly not enough. ;-)



> I discovered this while trying to build and run sc-im with XLSX_EXPORT support.

That's cool.

> A new release with this fix would be nice btw.

Sure. On its way.

**Comment by jmcnamara** [comment]
Version 1.0.8 has been released. Thanks for the report/fix.

**Pull request merged**
