### PR TITLE
fix cocoapods includes

### PR DESCRIPTION
**Pull request by atomiix**
Hi,

I had an issue with cocoapods : 'xlsxwriter/third_party/queue.h' file not found

This PR fix the problem ;)

### CODE REVIEW

**Comment by jmcnamara** [comment]
Thanks for the report.

It is a little odd that I haven't had a similar report from other people using the libxlsxwriter cocoapod. So I'm a little bit wary that this might fix an issue in your environment and break it in others.

There is a complete XCode libxlsxwriter cocoa project [here](https://github.com/lrossi/libxlsxwriterCocoaExamples). Can you try that and see if it works and if so why it is different from your project.

Thanks.

John.

**Comment by atomiix** [comment]
I just tried the demo project and it worked.

It doesn't work in my project because I use "use_frameworks!" on my Podfile (which is recommended when the project is a swift project) but this PR doesn't affect Podfile without "use_frameworks!"

Maybe @lrossi can confirm ?

Thank you.

Thomas

**Comment by lrossi** [comment]
Thanks @atomiix for pointing this out!
 
The `use_frameworks!` directive is strictly needed when there is at least one pod written in Swift included in the Podfile, and this is possibly a frequent case for people using libxlsxwriter in Swift. Unfortunately, as @atomiix noticed, I didn't run into this issue while writing the example since I'm not importing pods other than libxlsxwriter itself.

So, just to recap: the problem with the current Podfile is due to the headers being flattened into a single root directory when building the pod as a framework, so that `#include` directives referring to subdirectories make the compilation fail.

The proposed solution replaces occurrences of

```C
#include "xlsxwriter/third_party/queue.h"
```
with
```C
#include "queue.h"
```

and occurrences of

```C
#include "xlsxwriter/third_party/minizip/zip.h"
```
with
```C
#include "zip.h"
```

While this works fine when using the `use_frameworks!` directive in the Podfile, it breaks the compilation (at least in my tests) in the other cases, when the directory structure of the headers is preserved (because of a specific opt-in through the `header_mappings_dir`option in the Podspec... That I explicitly added with the intent of preserving the directory structure so that the `#include` directives referring to subdirectories don't break the compilation 😊).

A possible solution would be to *always* flatten all the headers into a single directory (i.e. to remove the `header_mappings_dir` option) and then to apply the proposed patch. However, I can see a couple of disadvantages in this solution:

1. Weird things could happen in case two headers with the same name are available in two different subdirectories that are then flattened into the same root directory. While this is not the case right now, it could possibly be in the future without anyone noticing it.
2. Having a script that modifies the source code only when building it through CocoaPods could be difficult to maintain.

However, maybe this will soon no more be needed since in the very latest CocoaPods's [CHANGELOG](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md) there is this line:

```Framework pods that have a header_mappings_dirs set will now produce frameworks with headers that respect the nesting.```

So it seems this was a problem with CocoaPods itself, that has now been fixed. However, at the time of writing, the fix is included in the `master` branch but not yet in a public CocoaPods release. Maybe we could wait for a new version of CocoaPods to come out and then test again, while referring to the @atomiix's fork as a temporary fix in the meantime. What do you think?

Thank you all.

**Comment by atomiix** [comment]
Thanks @lrossi for your answer.

I think you're right, we can wait for the new cocoapods version and use my fork as a temporary fix.
When the new version will be out, I'll try it ASAP.

BTW thank you @jmcnamara for this awesome library :)

Thomas

**Comment by jmcnamara** [comment]
@lrossi Thanks for the detailed analysis. I'll leave this as a documented know issue for now (once I've added it to the docs).

**Comment by jmcnamara** [comment]
@atomiix Was there an update to cocoapods to resolve this issue. I can see from their changelog that there was at least one release after the discussion above.

**Comment by lrossi** [comment]
Yes, a new release is currently in beta. However, since CocoaPods users need to explicitly opt-in to install beta versions, I'd suggest waiting for the final release before closing this issue. Furthermore, even though the latest CocoaPods release (mostly) fixes the problem, it seems that some tweaks to our Podspec are required so that the spec can work properly both with and without `use_frameworks!`. I'm working to propose an update to the Podspec and I'll then send a PR.

**Comment by jmcnamara** [comment]
Superseded by pull request #50. Closing.

**Pull request closed without merging**
