### PR TITLE
CMake: Check for third party libraries using pkgconfig

### PR DESCRIPTION
**Pull request by diizzyy**
Try to find libraries using pkgconfig and fallback to old behaviour if that fails

### CODE REVIEW

**Comment by jmcnamara** [comment]
Sorry for now getting to this sooner. Merged. Thanks.

**Comment by diizzyy** [comment]
Thanks for merging it! :-)

**Comment by jmcnamara** [comment]
I may need to revert this change since it is causing problems upstream in the `vcpkg`. That is the main method of consumption of libxlsxwriter on Windows so I need to prioritise it. I see that this patch was picked up by FreeBSD ports so that is also an important consideration.

Could you look at the following `vcpkg` issues and see if there can be a solution that works with both:

https://github.com/microsoft/vcpkg/issues/43653
https://github.com/microsoft/vcpkg/pull/43674

**Comment by dg0yt** [comment]
You don't have to take action for vcpkg. https://github.com/microsoft/vcpkg/pull/43674 is completely sufficient for vcpkg.

However, the issues I mentioned in https://github.com/microsoft/vcpkg/pull/43674#issuecomment-2650236897 deserve some consideration nevertheless.

**Comment by diizzyy** [comment]
Since Windows is broken just wrap ```find_package(PkgConfig)``` in ```if (UNIX)``` ?

**Comment by jmcnamara** [comment]
I'll look into a fix that works with Unix and Windows.

**Comment by dg0yt** [comment]
FTR it is not "Windows" but MSVC. (MinGW and clang-cl probably won't complain.)

**Comment by dg0yt** [comment]
And generally, using LD_FLAGS directly is very different from good CMake practice.

**Comment by jmcnamara** [comment]
> Try to find libraries using pkgconfig and fallback to old behaviour if that fail

I should have asked this at the time the PR was submitted but was the issue with the existing `find_package()` behaviour that using `pkg_check_modules()` fixes?

**Comment by diizzyy** [comment]
To be honest I don't recall exactly but something was half working with the "custom" variant rather than using pkgconfig.

If we can consider using a slightly newer vesion of CMake you can make this cleaner by importing libraries using the GLOBAL argument.
```
Added in version 3.6: The IMPORTED_TARGET argument will create an imported target named PkgConfig::<prefix> that can be passed directly as an argument to [target_link_libraries()](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries).

Added in version 3.13: The GLOBAL argument will make the imported target available in global scope.
```

**Comment by dg0yt** [comment]
> if there is a build or link error I will resolve it with `find_package`.

You may need to fix the order of library linking. In particular, put zlib libraries after minizip libraries. minizip depends on zlib, and with "traditional" linkers and static libs, the order matters.

**Comment by diizzyy** [comment]
So you're going do a regression? The only fix you need to do is already committed? There's also a bunch of repos that have adopted this approach so you might want to consider the aftermatch potentially breaking several repos including Debian (and Ubuntu), SUSE, Arch to mention a few?

**Comment by jmcnamara** [comment]
> So you're going do a regression?

It is not a regression if it isn't fixing something that is broken. It is just removing something that may or may not be needed. At the moment I don't have any evidence that it is needed so I'm going to remove it. If you can provide an example where it doesn't build with `find_package` I will put it back `pkgconfig` back in.



> ou might want to consider the aftermatch potentially breaking several repos including Debian (and Ubuntu), SUSE, Arch Linux, FreeBSD to mention a few?

It was building on all those system for several years before this change. But if there is something broken I will fix it, I just need to know what that is first.

**Comment by diizzyy** [comment]
Why using a custom solution instead of using a common framework that's used by the majority of projects?
I also just checked, it fixes proper detection of (at least) zlib and minizip witch otherwise fails.

```
CMake Error at cmake/FindMINIZIP.cmake:93 (file):
  file STRINGS file "/usr/local/include/zlib.h" cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:233 (find_package)


CMake Error at cmake/FindPackage.cmake:180 (message):
  Unable to find requested MINIZIP libraries.
Call Stack (most recent call first):
  cmake/FindMINIZIP.cmake:121 (RequiredPackageFound)
  CMakeLists.txt:233 (find_package)
```

**Comment by jmcnamara** [comment]
> Why using a custom solution instead of using a common framework that's used by the majority of projects?

Because it breaks the vcpkg downstream.



> CMake Error at cmake/FindMINIZIP.cmake:93 (file):

How do I reproduce this?

**Comment by diizzyy** [comment]
Looking the vcpkg repo you should be able to get rid of the custom module in this repo and rely on CMake's builtin logic alone (find_package) and on the other platforms pkgconfig .pc files) as they're available on "everything" else.

How to reproduce, I can't say for OpenSUSE but in FreeBSD you can see the issue using the ports collection (tree).

**Comment by jmcnamara** [comment]
> but in FreeBSD you can see the issue using the ports collection (tree).

Thanks. I was able to reproduce it with a version of FreeBSD 14.2 in a VM. 

While it could be fixed in the `FindMinizip.cmake` file I agree that it is best to just ditch that file at this point. As such I've removed the custom cmake files and fixed `CMakeLists.txt` so that it uses `find_package(unofficial-minizip)` on MSVC and `PkgConfig` and `pkg_check_modules()` on all other platforms. This should allow it to compile everywhere without any platform specific patches. I've tested it with MSVC, Ubuntu, FreeBSD and macOS.

If you get a chance you can test it too.

**Comment by dg0yt** [comment]
> > but in FreeBSD you can see the issue using the ports collection (tree).
> 
> Thanks. I was able to reproduce it with a version of FreeBSD 14.2 in a VM.

So what is the error? Is it a secret?

> I've removed the custom cmake files and fixed `CMakeLists.txt` so that it uses `find_package(unofficial-minizip)` on MSVC and `PkgConfig` and `pkg_check_modules()` on all other platforms.

So probably we will continue to patch in vcpkg, to *not* switch configuration by platform, and to not have zlib once from minizip pkgconfig and once from CMake, with static library linkage.

Apart from that, I don't encourage adopting vcpkg lock-in patterns.

BTW good find modules allow users to seed the cache variables. Usually this is enough to deal with unusual platforms for single-config shared-library-linkage.

**Comment by jmcnamara** [comment]
> So what is the error? Is it a secret?

The error was the same as the one you showed above for OpenSUSE:

```
CMake Error at cmake/FindMINIZIP.cmake:93 (file):
  file STRINGS file "/usr/local/include/zlib.h" cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:233 (find_package)
```

I think this occurs when the zlib includes are in `/usr/include` and the minizip includes are in `/usr/local/include` but I didn't dig into it any deeper than that. The logic of the `FindMinizip.cmake` file wasn't very robust.

> to not have zlib once from minizip pkgconfig and once from CMake, with static library linkage.

Are you referring to linking minizip with `MINIZIP_LINK_LIBRARIES` and thus getting `/path/to/minipzip.so` instead of  `-lminizip`, or something else?


> BTW good find modules allow users to seed the cache variables. Usually this is enough to deal with unusual platforms for single-config shared-library-linkage.

Could you give some suggestion about what would be useful in relation to the libxlsxwriter `CMakeLists.txt` file?

**Comment by dg0yt** [comment]
> I think this occurs when the zlib includes are in `/usr/include` and the minizip includes are in `/usr/local/include` but I didn't dig into it any deeper than that.

So the find module assumed that it could find the version of minizip from `zlib.h`, but that header belongs to a different package and location in some installations.
It might have been possible to just ignore the version of minizip when there is no reliable source for that information.

**Comment by jmcnamara** [comment]
Okay folks. I appear to have come up with a "solution" that doesn't please anyone. My apologies for that. Let's try again and I'll see if I can do better this time. In return may I ask you to be as technically explicit as possible in your replies. 

@dg0yt Let me start with this, from above:

> > I've removed the custom cmake files and fixed `CMakeLists.txt` so that it uses `find_package(unofficial-minizip)` on MSVC and `PkgConfig` and `pkg_check_modules()` on all other platforms.
> 
> So probably we will continue to patch in vcpkg, to _not_ switch configuration by platform, and to not have zlib once from minizip pkgconfig and once from CMake, with static library linkage.

Are you saying that it would be preferable for `libxlsxwriter` to continue to use the `cmake/FindMINIZIP.cmake` file? And by extension not use pkgconfig?

**Pull request merged**
