### PR TITLE
make C++ tests work with USE_SYSTEM_MINIZIP

### LINKED ISSUE #358: C++ tests fail with USE_SYSTEM_MINIZIP
After https://github.com/jmcnamara/libxlsxwriter/commit/dd9b1772355f2bae0d31ecda2494f008ce908705, `USE_SYSTEM_MINIZIP=1 make test` fails with
```
make[1]: Entering directory '/build/source/test/cpp'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `_add_file_to_zip':
/build/source/src/packager.c:1500: undefined reference to `zipOpenNewFileInZip4_64'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1528: undefined reference to `zipWriteInFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1539: undefined reference to `zipCloseFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_packager_new':
/build/source/src/packager.c:114: undefined reference to `zipOpen'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_create_package':
/build/source/src/packager.c:1604: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1595: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1643: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1655: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `_add_buffer_to_zip':
/build/source/src/packager.c:1554: undefined reference to `zipOpenNewFileInZip4_64'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1568: undefined reference to `zipWriteInFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1576: undefined reference to `zipCloseFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_create_package':
/build/source/src/packager.c:1663: undefined reference to `zipClose'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:37: test_compilation] Error 1
make[1]: Leaving directory '/build/source/test/cpp'
make: *** [Makefile:107: test_cpp] Error 2
```

### PR DESCRIPTION
**Pull request by dotlambda**
closes #358

### CODE REVIEW

**Comment by jmcnamara** [comment]
What is this fixing?

**Comment by dotlambda** [comment]
> What is this fixing?

Running `USE_SYSTEM_MINIZIP=1 make test` doesn't work without:
```
make[1]: Entering directory '/build/source/test/cpp'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `_add_file_to_zip':
/build/source/src/packager.c:1500: undefined reference to `zipOpenNewFileInZip4_64'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1528: undefined reference to `zipWriteInFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1539: undefined reference to `zipCloseFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_packager_new':
/build/source/src/packager.c:114: undefined reference to `zipOpen'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_create_package':
/build/source/src/packager.c:1604: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1595: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1643: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1655: undefined reference to `zipClose'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `_add_buffer_to_zip':
/build/source/src/packager.c:1554: undefined reference to `zipOpenNewFileInZip4_64'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1568: undefined reference to `zipWriteInFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: /build/source/src/packager.c:1576: undefined reference to `zipCloseFileInZip'
/nix/store/ffcrrgb6k5h7crr93dj90bi9fy1jvj16-binutils-2.35.1/bin/ld: ../../src/libxlsxwriter.a(packager.o): in function `lxw_create_package':
/build/source/src/packager.c:1663: undefined reference to `zipClose'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:37: test_compilation] Error 1
make[1]: Leaving directory '/build/source/test/cpp'
make: *** [Makefile:107: test_cpp] Error 2
```

**Comment by jmcnamara** [comment]
Ok. Best to open a bug report then since this would also fail when using OpenSSL. And maybe something else. I'll need to look into it. 

I also need to get Travis working again or port the CI to GitHub Actions. The CI would have caught this. 😡

**Comment by sjmulder** [comment]
I encountered the same while packaging in pkgsrc and opened #359 before seeing this one, which is indeed the same except I also added the OpenSSL MD5 case. #360 is slightly related.

**Comment by jmcnamara** [comment]
Fixed in #359. Thanks for the report.

**Pull request closed without merging**
