### PR TITLE
improve cmake file for MSVC

### PR DESCRIPTION
**Pull request by jimzshi**
- optional project and binary name
- optimize output folder tree for MSVC configurations
- fix compiler flags issues for MSVC
- fix minor issue when findzlib

### CODE REVIEW

**Comment by jmcnamara** [comment]
@jimzshi Thanks for the fix.

@Alexhuszagh and @burlen can you do a quick review.

**Comment by Alexhuszagh** [comment]
Looks excellent, with one small change: zlib is not required for building the library, only for building the tests or examples, so I would keep the if statement to find zlib only if the tests or examples are built.

Otherwise, this provides all possible build types and runtime flags with minimal additions: it looks great.

**Comment by jimzshi** [comment]
Thanks @jmcnamara and @Alexhuszagh 

btw @Alexhuszagh, I found it's not possible to build even only libxlsxwriter without knowing where is zlib.h. My test was run on Windows 10 with VS 2015, that's why I removed that if statement. could you please help with a double check?

Cheers.

**Comment by Alexhuszagh** [comment]
@jimzshi Actually you're right, I just used a few cross-compiling Windows environments (Fedora MinGW, MXE) and I ran into the same error for the CMake and Makefile build system. Sorry about that, I guess I was mistaken. Thank you.

**Comment by jmcnamara** [comment]
@jimzshi I tested this and it looks good. I was able to build a project, and from there a lib, as follows:

    cd cmake
    cmake .. -G "Visual Studio 14 2015 Win64"

Based on that, and @Alexhuszagh's  comments,I will merge the PR.

Could you provide some details, about how to use this to build something beyond a basic project. Is it possible to build a DLL or these examples?

**Comment by jmcnamara** [comment]
Merged.

**Comment by jimzshi** [comment]
thanks @jmcnamara for merging. sorry for the late reply, but i was occupied by something else. 

DLL and examples are still not working in MSVC, i'll fix them in separate PR.

**Pull request merged**
